### ISSUE TITLE
Backup fails with permissions error

### ISSUE THREAD

**Issue by thomasdpage** [Kaiede/docker-minecraft-bedrock-backup#1]
Hi,

The backup is failing with the following error:

```
Content Read: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/build-battle/json: dial unix /var/run/docker.sock: connect: permission denied
```

I'd prefer not to run this with elevated permissions - is that possible?

**Comment by Kaiede** [comment]
The container de-elevates permissions by default, reading the owner/group of the `/backups` folder. This is similar to how the minecraft-bedrock-server container works (the two use the same tool to do it). I run it as a non-root user myself, and 100% recommend doing the same.

It’s worth noting that since the backup tool does require access to `docker attach` to tell the other containers to prepare for a backup (flushing to disk, and placing autosave on hold for a second or two), it still still gives more access to docker itself than I’d like, sadly, but I still try to limit the permissions as much as possible. I keep my gaming servers in their own VM to further isolate them from anything important. 

To get this to work as a non-root user though, I did have to make sure the *group* is set correctly on the folder, since the user being in the correct group by itself is not enough. Using my home server as an example, I added my user to the docker group so I could use docker commands without sudo (https://docs.docker.com/engine/install/linux-postinstall/). So I have `myuser` in the `docker` group. `mkdir` will create folders with the user/group of `myuser:myuser` by default, which isn’t good enough to provide the de-elevated container with access to the docker socket file. If I chown the backups folder to `myuser:docker` instead, it works. So this _should_ also work in your case. 

Further detail of the user/group settings on the docker socket file, and my backup folder, from my Ubuntu host:
```
srw-rw---- 1 root docker 0 Apr 28 11:40 /var/run/docker.sock
drwxrwxr-x  2 myuser docker 4096 May  8 22:59 /home/myuser/Bedrock/Backups
```

Inside the Backups folder, all the backups will be owned by `myuser:docker` as well when written by the tool.

```
-rw-r--r-- 1 myuser docker  79415611 May  8 22:59 'Ered Luin.20210508-225922.mcworld'
```

Let me know if these instructions help. This is probably the easiest bit to get tripped up on, and I would be happy to update the readme with better details if this is the issue.

**Comment by thomasdpage** [comment]
Thanks for the excellent and detailed reply!

Missing permissions - I missed that and it does mention that in your instructions.  I've made the change and I'm now getting a different error message:

```
minecraft-backup_1  | [ PTYProcess:sh ] [ TRACE ] Content Read: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/build-battle/json: dial unix /var/run/docker.sock: connect: permission denied
```

Unless I've missed something, I suspect this might be because I'm running Docker in rootless mode (for the first time).  Moving these game servers to a separate VM is a good idea too actually, now you mention it.

**Comment by Kaiede** [comment]
Maybe I’m missing something but the error message looks the same, just with the logging prefix on the front? “Content Read:” in both cases is coming from PTYProcess (the wrapper for talking to `docker attach` from Swift), so it’s the same line of code in the tool.

Unfortunately, I haven’t tried running docker in rootless mode, so I’m not 100% sure how to proceed (I’m rather new to docker). Especially if the UID/GID pair you are using has permission to run docker commands on the host, since that should be all that’s needed. I assume you adjusted the docker-compose.yml to map in the user’s docker.sock rather than the system-level one already? Another thing that I’d be curious about is what UID/GID `entrypoint-demoter` is actually picking, and if it is different than what is set on the host folder storing the backups. It’s possible that docker might be mapping the permissions in a way that breaks entrypoint-demoter in the way I need it to work? Again, just not familiar enough with rootless docker, so I am guessing a lot here. 

While hitting this error, the container will continue to run on the backup interval, so it’s possible to exec into it via a shell and poke around. It has a copy of the docker.io package installed, so doing some manual testing is possible in this state.

**Comment by thomasdpage** [comment]
You're right, the error was exactly the same.  I've built a new VM, installed Docker non-rootless, and re-deployed the containers.  The backup is failing and I'm not sure why:

```
mc-backup           | [ PTYProcess:sh ] [ TRACE ] Expecting: ["Files are now ready to be copied"] (PTYKit/PTYProcess.swift:120)
mc-backup           | [ PTYProcess:sh ] [ TRACE ] Starting RunLoop (PTYKit/PTYProcess.swift:123)
mc-backup           | [ PTYProcess:sh ] [ TRACE ] Background Reading Start (PTYKit/PTYProcess.swift:162)
mc-backup           | [ PTYProcess:sh ] [ TRACE ] Content Read: save query
mc-backup           |  (PTYKit/PTYProcess.swift:147)
mc-backup           | [ PTYProcess:sh ] [ TRACE ] No Match (PTYKit/PTYProcess.swift:156)
mc-backup           | [ PTYProcess:sh ] [ TRACE ] Content Read: Data saved. Files are now ready to be copied.
mc-backup           | Bedrock level/db/023512.ldb:1465, Bedrock level/db/023318.ldb:158737, Bedrock level/db/023514.ldb:1464, Bedrock level/db/023510.ldb:12703, Bedrock level/db/CURRENT:16, Bedrock level/db/MANIFEST-023515:371, Bedrock level/db/023516.ldb:1454, Bedrock level/db/023517.log:0, Bedrock level/level.dat:2209, Bedrock level/level.dat_old:2209, Bedrock level/levelname.txt:13
mc-backup           |  (PTYKit/PTYProcess.swift:147)
mc-backup           | [ PTYProcess:sh ] [ TRACE ] Match Found (PTYKit/PTYProcess.swift:151)
mc-backup           | [ PTYProcess:sh ] [ TRACE ] Background Reading Stop (PTYKit/PTYProcess.swift:177)
mc-backup           | [ PTYProcess:sh ] [ TRACE ] Background Reading Cleanup (PTYKit/PTYProcess.swift:170)
mc-backup           | Starting Backup of worlds at: /opt/containers/minecraft-bedrock/build-battle-data/worlds
mc-backup           | Backup Failed...
mc-backup           | [ PTYProcess:sh ] [ TRACE ] Sending: save resume
mc-backup           |  (PTYKit/PTYProcess.swift:97)
mc-backup           | [ PTYProcess:sh ] [ TRACE ] Expecting: ["Changes to the level are resumed", "A previous save has not been completed"] (PTYKit/PTYProcess.swift:120)
```

My compose file looks like this and permissions seem OK - suspect I've made a mistake in the config somewhere.

```
version: '3.4'

services:

  minecraft-backup:
    image: kaiede/minecraft-bedrock-backup
    container_name: mc-backup
    restart: always
    depends_on:
      - "build-battle"
    environment:
        BACKUP_INTERVAL: "1h"
        TZ: "Europe/London"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /mnt/qnap/cbackups/minecraft-bedrock:/backups
      - /opt/containers/minecraft-bedrock:/build-battle

  build-battle:
    image: itzg/minecraft-bedrock-server
    container_name: build-battle
    environment:
      EULA: "TRUE"
      SERVER_NAME: build-battle
      # LEVEL_NAME: build-battle
      LEVEL_TYPE: flat
      GAMEMODE: creative
      DIFFICULTY: easy
      FORCE-GAMEMODE: "TRUE"
    ports:
      - 19132:19132/udp
    volumes:
      - /opt/containers/minecraft-bedrock/build-battle-data:/data
    stdin_open: true
    tty: true
```

My `config.json`:

```
{
    "servers": {
        "build-battle": "/opt/containers/minecraft-bedrock/build-battle-data/worlds"
    },
    "trim": {
        "trimDays":   2,
        "keepDays":   14,
        "minKeep":    2
    }
}
```
