### ISSUE TITLE
entrypoint-demoter causes permission denied on /var/run/docker.sock

### ISSUE THREAD

**Issue by processor286** [Kaiede/docker-minecraft-bedrock-backup#10]
Running with Docker 19.03.15 on OpenSUSE

Compose:

```
  backup:
    image: kaiede/minecraft-bedrock-backup
    restart: always
    depends_on:
      - "bedrock"
    environment:
      BACKUP_INTERVAL: "3h"
      TZ: "Europe/London"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /nas/bedrock/backups:/backups
      - bedrock:/server
```

Always returns this:

`Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/bedrock_bedrock_1/json: dial unix /var/run/docker.sock: connect: permission denied
`

If I change compose to add entrypoint:

`entrypoint: tail -f /dev/null `

Then I can exec the container and run entry.sh on its own , and it works fine.

If I run with this though:

`/usr/local/bin/entrypoint-demoter --match /backups --debug --stdin-on-term  stop /opt/bedrock/entry.sh`

Then we see permission denied on the docker sock.
