### ISSUE TITLE
Permission Error

### ISSUE THREAD

**Issue by weihao** [Kaiede/docker-minecraft-bedrock-backup#21]
```
Performing Backups

[ PTYProcess:sh ] [ TRACE ] Launching (PTYKit/PTYProcess.swift:72)

[ PTYProcess:sh ] [ TRACE ] Sending: save hold

 (PTYKit/PTYProcess.swift:97)

[ PTYProcess:sh ] [ TRACE ] Expecting: ["Saving", "The command is already running"] (PTYKit/PTYProcess.swift:120)

[ PTYProcess:sh ] [ TRACE ] Starting RunLoop (PTYKit/PTYProcess.swift:123)

[ PTYProcess:sh ] [ TRACE ] Background Reading Start (PTYKit/PTYProcess.swift:162)

[ PTYProcess:sh ] [ TRACE ] Content Read: WARNING: Error loading config file: /root/.docker/config.json: open /root/.docker/config.json: permission denied

 (PTYKit/PTYProcess.swift:147)

[ PTYProcess:sh ] [ TRACE ] No Match (PTYKit/PTYProcess.swift:156)

[ PTYProcess:sh ] [ TRACE ] Content Read: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/survival/json: dial unix /var/run/docker.sock: connect: permission denied

 (PTYKit/PTYProcess.swift:147)

[ PTYProcess:sh ] [ TRACE ] No Match (PTYKit/PTYProcess.swift:156)

[ PTYProcess:sh ] [ TRACE ] Terminated (PTYKit/PTYProcess.swift:76)

[ PTYProcess:sh ] [ TRACE ] Background Reading Stop (PTYKit/PTYProcess.swift:177)

[ PTYProcess:sh ] [ TRACE ] Background Reading Cleanup (PTYKit/PTYProcess.swift:170)

The operation could not be completed. (Bedrockifier.WorldBackupError error 0.)
```

permission for the backups folder is `drwxrwxrwx`

```
version: "3.8"

services:
  backup:
    image: kaiede/minecraft-bedrock-backup
    restart: unless-stopped
    depends_on:
      - "survival"
    environment:
      BACKUP_INTERVAL: "12h"
      TZ: "America/New_York"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./backups:/backups
      - ./survival:/survival
  survival:
    image: itzg/minecraft-bedrock-server
    container_name: survival
    restart: unless-stopped
    environment:
      EULA: "TRUE"
    ports:
      - 19132:19132/udp
    volumes:
      - ./survival:/data
    stdin_open: true
    tty: true
```
