### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by g6ai** [Kaiede/docker-minecraft-bedrock-backup#33]
I had used the previous `config.json` without problem. Today I've just upgraded this image, and added the new `config.yml` (the `config.json` is deleted). The console output is:

```console
time="2022-01-07T18:01:08Z" level=debug msg="Using /backups to match uid and gid"
time="2022-01-07T18:01:08Z" level=debug msg="Resolved UID=0 from match path"
time="2022-01-07T18:01:08Z" level=debug msg="Resolved GID=0 from match path"
time="2022-01-07T18:01:08Z" level=debug msg="stdin is detached, so forwarding is disabled"
The operation could not be completed. No such file or directory
[INFO] sleeping 24h...
```

My configs are:

`docker-compose.yml`:
```yaml
version: '3.7'

services:
  server:
    image: itzg/minecraft-bedrock-server
    container_name: mbd_server
    environment:
      EULA: "TRUE"
    ports:
      - 19132:19132
      - 19132:19132/udp
    volumes:
      - /Users/gbai/minecraft_bedrock:/data
    stdin_open: true
    tty: true
    sysctls:
      net.ipv4.ip_local_port_range: 39132 39133
  backup:
    image: kaiede/minecraft-bedrock-backup
    container_name: mbd_backup
    restart: always
    depends_on:
      - "server"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /Users/gbai/minecraft_bedrock_backups:/backups
      - /Users/gbai/minecraft_bedrock:/server

volumes:
  bds: {}
```

`config.yml`:
```yaml
containers:
  bedrock:
    - name: mbd_server
      worlds:
        - /server/worlds/Bedrocklevel
schedule:
  interval: 30m
trim:
  trimDays: 5
  keepDays: 15
  minKeep: 10
loggingLevel: trace
```

Also noted:
* It looks like the `config.yml` is not read at all, because I see `level=debug` in the console output despite the setting of `loggingLevel: trace`.
* There is an `unhealthy` flag file in the backups folder.
