### ISSUE TITLE
[Feature request] Ability to specify backup subpath

### ISSUE THREAD

**Issue by digitalentity** [Kaiede/docker-minecraft-bedrock-backup#5]
I'm backing up multiple things to a single NFS share (named volume in Docker). Since Docker doesn't support attaching subdirectories of a named volume, I need a separate one for Minecraft backups.

Can you please add an environment variable to choose a subfolder under `/backups` to look for config and upload backups to?

**Comment by Kaiede** [comment]
While not documented (because I didn’t test it), this probably already works. You should be able to set the following variable:

DATA_DIR - Set this to the path where you want the backups. It defaults to /backups if it isn’t set. But you can set it to any path in the container you want.

**Comment by digitalentity** [comment]
Thanks, but that solution unfortunately doesn't work.

Snippet of docker-compose file:

```
  backup:
    container_name: minecraft_backup
    image: kaiede/minecraft-bedrock-backup
    restart: always
    depends_on:
      - "private"
    environment:
        DATA_DIR: "/backups_root/minecraft"
        BACKUP_INTERVAL: "6h"
        TZ: "America/Los_Angeles"
```

Errors from the container:

```
backup_1   | time="2021-07-13T23:05:01-07:00" level=debug msg="Using /backups to match uid and gid"
backup_1   | time="2021-07-13T23:05:01-07:00" level=fatal msg="Failed to resolve IDs" error="unable to inspect match path: stat /backups: no such file or directory"
```

**Comment by Kaiede** [comment]
And if you keep the volume mounted at /backups rather than moving it?

It looks like the use of entry point demoter is the problem in that it doesn't seem great for allowing the volume to be moved, but it should allow sub-folders to still be used.

**Comment by digitalentity** [comment]
That's not a good option either, unfortunately, volume root is owned by `nobody:nogroup` (historical reasons, too many servisec depend on that), and that would not allow the backup service to interact with docker properly.

**Comment by Kaiede** [comment]
Overriding the UID/GID is something you’ll want to do in this situation. 

> `UID` and `GID`: Use these when the automatic demotion doesn't work for you. They aren't necessary when running rootless.

**Comment by digitalentity** [comment]
Great, thanks. It actually worked. I'm running docker at root, so I had to use 0:0 as uid/gid:

```
  backup:
    container_name: minecraft_backup
    image: kaiede/minecraft-bedrock-backup
    restart: always
    depends_on:
      - "private"
    environment:
        UID: 0
        GID: 0
        DATA_DIR: "/backups/minecraft"
        BACKUP_INTERVAL: "6h"
        TZ: "America/Los_Angeles"
    volumes:
      - BackupsRoot:/backups
      - MinecraftServerRoot:/private-server
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config.json:/backups/minecraft/config.json
```

`BackupsRoot` and `MinecraftServerRoot` are NFS-backed volumes, `config.json` resides alongside `docker-compose.yaml` for easier maintenance and is binded to the right path by docker.
