### ISSUE TITLE
no backup output after updating server

### ISSUE THREAD

**Issue by skilson** [Kaiede/docker-minecraft-bedrock-backup#7]
first off - big fan of the container and I've successfully used it for many months

requesting a sanity check after most recent bedrock server update I'm getting this in my backup container logs:

```time="2021-10-04T22:19:48-05:00" level=debug msg="Using /backups to match uid and gid",
time="2021-10-04T22:19:48-05:00" level=debug msg="Resolved UID=1028 from match path",
time="2021-10-04T22:19:48-05:00" level=debug msg="Resolved GID=65538 from match path",
time="2021-10-04T22:19:48-05:00" level=debug msg="stdin is detached, so forwarding is disabled",
Performing Backups,
[ PTYProcess:sh ] [ TRACE ] Launching (PTYKit/PTYProcess.swift:72),
[ PTYProcess:sh ] [ TRACE ] Sending: save hold,
 (PTYKit/PTYProcess.swift:97),
[ PTYProcess:sh ] [ TRACE ] Expecting: ["Saving", "The command is already running"] (PTYKit/PTYProcess.swift:120),
[ PTYProcess:sh ] [ TRACE ] Starting RunLoop (PTYKit/PTYProcess.swift:123),
[ PTYProcess:sh ] [ TRACE ] Background Reading Start (PTYKit/PTYProcess.swift:162),
[ PTYProcess:sh ] [ TRACE ] Content Read: WARNING: Error loading config file: /root/.docker/config.json: open /root/.docker/config.json: permission denied,
 (PTYKit/PTYProcess.swift:147),
[ PTYProcess:sh ] [ TRACE ] No Match (PTYKit/PTYProcess.swift:156),
[ PTYProcess:sh ] [ TRACE ] Background Reading Cleanup (PTYKit/PTYProcess.swift:170),
[ PTYProcess:sh ] [ TRACE ] Sending: Q (PTYKit/PTYProcess.swift:97)
```

The Error loading config.json has me the most puzzled and I've done a lot of troubleshooting around that file:
- ran `ls -l`
- tried recreating file in GUI
- tried recreating file in CLI
- ran `chown` on new file(s)
- ran `chmod` on new file(s)

At this point I'm pretty sure it's able to access and read the file because if I pass an invalid container name it throws the proper error or if using an empty .json it also reports the proper error.

I went through the `BedrockifierCLI` and `PtyKit` repos and based on them I think I'm just hitting the timeout or perhaps I'm totally misreading it.

**Comment by Kaiede** [comment]
The config.json error came up in #2. That specific error is a red herring as it’s pretty normal to run into. That’s **docker** complaining when `docker attach` is started, not BedrockifierCLI. “Content Read:” prefixes anything coming from the `docker attach` process.

The more puzzling thing is why the attach is successful, but it doesn’t actually spit anything out. That seems to potentially be something related to how the server container is configured, more than anything else.

I recently updated to 1.17.33 on my local servers as well, and backups are all running as expected. My backup container backs up two separate bedrock containers, and both seem to be working. 

Can you share how your docker-compose.yml?

**Comment by skilson** [comment]
here's a test compose I setup and get the same results:
```
version: "3.3"
services:
  minecraft-bedrock-server:
    container_name: mc-test
    restart: unless-stopped
    ports:
      - "19130:19132/tcp"
      - "19130:19132/udp"
    environment:
      - EULA=${EULA}
      - OPS=${OPS}
      - TZ=${TZ}
    volumes:
      - "/volume1/docker/mc-bedrock-test:/data"
    image: itzg/minecraft-bedrock-server

  minecraft-bedrock-backup:
    container_name: mc-backup-test
    restart: unless-stopped
    environment:
      - TZ=${TZ}
      - BACKUP_INTERVAL=${BACKUP_INTERVAL}
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/volume1/docker/mc-bedrock-backup-test:/backups"
      - "/volume1/docker/mc-bedrock-test:/bedrock_server"
    image: kaiede/minecraft-bedrock-backup
```
